---
# tasks file for iTrust
- name: "Check if iTrust dir exists in ~"
  stat:
    path: /home/ubuntu/iTrust
  register: dir_already_present

- name: "Clone the iTrust repo"
  tags: 
    - clone
  git:
    repo: https://{{ usertoken }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
    dest: /home/ubuntu/iTrust
    clone: true
    update: false
  when: not dir_already_present.stat.exists

- name: "Fix Spring Application context properties"
  tags: 
    - fix
  block:
    - name: "Check if application.yml already exists"
      stat:
        path: /home/ubuntu/iTrust/iTrust2/src/main/resources/application.yml
      register: app_yml_already_present
    - name: "Rename application.yml.template -> application.yml"
      become: true
      shell:
        cmd: 'mv application.yml.template application.yml'
        chdir: /home/ubuntu/iTrust/iTrust2/src/main/resources/
      when: not app_yml_already_present.stat.exists

    - name: "Update the spring.datasource.password value"
      shell:
        cmd: yq -i '.spring.datasource.password = "{{ db_pass }}"' application.yml
        chdir: /home/ubuntu/iTrust/iTrust2/src/main/resources/

- name: "Run tests"
  tags: 
    - test
  register: test_output
  shell:
    cmd: 'mvn -U -B clean test'
    chdir: /home/ubuntu/iTrust/iTrust2/

- debug:
    var: test_output.stdout_lines[-300:]